name: Check Secret
on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar API Key
        if: ${{ secrets.API_KEY }}
        run: echo "API Key configurada"
        
      - name: Error si falta
        if: ${{ !secrets.API_KEY }}
        run: |
          echo "Falta API_KEY en secrets"
          exit 1
